name: Daily Growth Digest

on:
  schedule:
    # Runs every day at 7:00 AM UTC (8:00 AM CET)
    - cron: '0 7 * * *'
  
  # Allows manual trigger from Actions tab
  workflow_dispatch:

jobs:
  generate-digest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Generate digest
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          python digest_final.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add output.html
          git diff --quiet && git diff --staged --quiet || (git commit -m "Daily digest update: $(date +'%Y-%m-%d')" && git push)
